export const pleasantScents = [
  "Freshly baked bread", "Coffee brewing", "Vanilla", "Lavender", "Citrus (orange)", "Cinnamon",
  "Freshly cut grass", "Chocolate", "Roses", "Peppermint", "Clean linen", "Coconut", "Pine needles",
  "Sandalwood", "Fresh rain", "Apple pie", "Honey", "Almonds", "Jasmine", "Freshly squeezed lemon",
  "Eucalyptus", "Ginger", "Sea breeze", "Warm cookies", "A campfire", "Mulled wine", "Autumn leaves",
  "Fresh strawberries", "Gardenia", "Tea brewing", "Sweet corn", "Tobacco (pipe)", "Freshly mowed lawn",
  "Caramel", "Warm spices", "Pomegranate", "Peach", "Lilac", "Sunblock", "Fresh mint", "Cloves",
  "Sugar cookies", "Grapefruit", "Campfire smoke", "Freshly peeled oranges", "Balsam fir", "Maple syrup",
  "Sweet pea", "Baby powder", "Almond blossom", "Fennel", "Freshly baked pastries", "Dill", "Cherries",
  "Cranberries", "Neroli", "Fresh vegetables", "Petunias", "Freshly washed hair", "Sage", "Buttercream frosting",
  "Blackberry", "Cardamom", "Fig", "Freshly grated nutmeg", "Rosewater", "White tea", "Climbing roses",
  "Freshly baked pizza", "Buttered popcorn", "Cinnamon rolls", "Sun-ripened tomatoes", "Wildflowers",
  "Freshly brewed herbal tea", "Coconut milk", "Saffron", "Sweet basil", "Tuberose", "Freshly picked apples",
  "Vanilla bean", "Raspberry", "Wisteria", "Freshly squeezed lime", "Sweet marjoram", "Pina colada", "Sea salt",
  "Mimosas", "Henna", "Freshly baked muffins", "Spiced cider", "Orange blossoms", "Toasted marshmallows",
  "Freshly baked croissants", "Acai", "Cucumber", "Honeydew melon", "Maple wood", "Freshly brewed coffee cake",
  "Poppyseed", "Elderflower", "Freshly baked bagels", "Blackberry sage", "Citrus zest", "Warm vanilla sugar",
  "Freshly picked cherries", "Butterscotch", "Fresh herbs", "Elderberry", "Freshly baked donuts", "Sweet perfume",
  "Lavender fields", "Jasmine tea", "Wild mint", "Mint chocolate", "Tansy", "Cardamom coffee", "Freshly baked brownies",
  "Sugar cookies with icing", "Cacao", "Rosemary", "Fresh fennel", "Sweet orange", "Herbal sachets", "Sweet tangerine",
  "Freshly baked scones", "Chamomile", "Sweet potato", "Freshly picked grapefruit", "Maple bacon", "Rosemary bread",
  "Coconut cake", "Fruity yogurt", "Meyer lemon", "Freshly baked tart", "Hibiscus", "Freshly brewed chai",
  "Buttery croissant", "Warm breadsticks", "S’mores", "Spiced pumpkin", "Freshly brewed iced tea", "Lemongrass",
  "Freshly made guacamole", "Chocolate chip cookies", "Sweet pea blossoms", "Freshly picked blackberries",
  "Almond butter", "Spicy chai", "Freshly baked empanadas", "Pear", "Freshly brewed matcha", "Maple pecan",
  "Sweet corn pudding", "Freshly baked quiche", "Tropical fruits", "Sweet chili", "Freshly baked biscuit",
  "Blackberry jam", "Almond croissant", "Freshly brewed espresso", "Lavender honey", "Warm apple cider",
  "Freshly made salsa", "Sweet marzipan", "French toast", "Freshly picked raspberries", "Gingerbread",
  "Lemon meringue", "Freshly baked cookies", "Sweet potato pie", "Citrus candle", "Freshly brewed coffee with cream",
  "Chocolate covered strawberries", "Freshly baked baguette", "Spicy caramel", "Sweet potato fries",
  "Freshly squeezed grapefruit juice", "Freshly baked fruit cake"
];

export const pungentScents = [
  "Rotten eggs", "Sewage", "Spoiled milk", "Decaying flesh", "Garbage", "Fish market", "Vomit", "Durian",
  "Moldy bread", "Sour cabbage", "Stale beer", "Skunk spray", "Burnt rubber", "Feces", "Old gym socks", "Wet dog",
  "Cigarette smoke", "Rotting vegetables", "Sour cream", "Musty basements", "Wet cardboard", "Spoiled meat",
  "Canned tuna", "Old cheese", "Rancid oil", "Mold", "Urine", "Dirty dishes", "Sour fruits", "Chemical waste",
  "Dead animals", "Pungent cheese", "Sourdough starter", "Stagnant water", "Body odor", "Old fish", "Rotted wood",
  "Old potatoes", "Dirt", "Sour milk", "Putrid fruit", "Decomposing leaves", "Foul breath", "Damp laundry",
  "Overcooked cabbage", "Sweaty feet", "Spoiled yogurt", "Burnt hair", "Old mayonnaise", "Curry leftovers",
  "Sour pickles", "Rotting seaweed", "Moldy cheese", "Peeled onions", "Stale bread", "Pet waste", "Old fish oil",
  "Chemical cleaners", "Old trash", "Rancid butter", "Burnt popcorn", "Sour grapes", "Decomposing garbage",
  "Foul-smelling flowers", "Sour dough", "Fungal infections", "Expired food", "Old leather", "Sour beer",
  "Rotted tomatoes", "Mildew", "Foul-smelling soap", "Petrol fumes", "Stale coffee", "Old spices", "Rancid nuts",
  "Sour apple cider", "Burnt toast", "Putrid pond", "Old ketchup", "Musty books", "Expired milk", "Decayed fruit",
  "Foul-smelling fish", "Sour wheat", "Old eggs", "Chemical spills", "Sour wine", "Decomposing insects", "Stale popcorn",
  "Old laundry", "Rancid mayonnaise", "Sour beans", "Foul-smelling rubber", "Spoiled salad", "Burnt sugar", "Old carpets",
  "Foul-smelling drains", "Sour berries", "Old crab", "Rotted turnips", "Sour tea", "Chemical fertilizers", "Spoiled pasta",
  "Moldy fruit", "Foul-smelling grease", "Old perfumes", "Sour clams", "Old tobacco", "Rotten garlic", "Stale biscuits",
  "Decomposing plants", "Sour fish sauce", "Expired sauces", "Old paint", "Chemical odor", "Sour dressing", "Old fish scales",
  "Moldy furniture", "Foul-smelling air fresheners", "Rancid peanut butter", "Sour doughnuts", "Old cleaning supplies",
  "Decomposed food waste", "Sour citrus", "Foul-smelling armpits", "Old rubber bands", "Moldy yogurt", "Sour milkshake",
  "Rotten cabbage", "Putrid leftovers", "Old pineapple", "Sour barbecue sauce", "Foul-smelling varnish", "Old cucumbers",
  "Rancid salad dressing", "Sour hoisin sauce", "Chemical odors from factories", "Decayed meat", "Foul-smelling trash cans",
  "Sour ketchup", "Old beans", "Rotted squash", "Foul-smelling litter boxes", "Old compost", "Sour seafood", "Burnt garlic",
  "Foul-smelling furniture polish", "Stale chips", "Decomposed vegetables", "Sour vinegar", "Old cough syrup", "Sour jello",
  "Rotting fish heads", "Foul-smelling incense", "Old grease traps", "Sour nutmeg", "Spoiled fruit juice", "Old saucepans",
  "Putrid smoke", "Foul-smelling candles", "Old baking powder", "Sour gum", "Decomposed animal waste", "Foul-smelling air ducts",
  "Stale pastries", "Old shoe odor", "Expired condiments", "Sour milk powder", "Foul-smelling exhaust fumes", "Old fish food",
  "Rancid cooking spray", "Sour tomato sauce", "Burnt chili", "Foul-smelling sneakers", "Stale pretzels", "Old salad greens",
  "Decomposed organic matter", "Sour ice cream", "Foul-smelling fish oil", "Old coffee grounds", "Sour nut butter",
  "Spoiled whipped cream", "Foul-smelling musty carpets", "Old salad dressing", "Rotted carrots", "Foul-smelling fish tanks"
];
